//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public long uid { get; }
        public long product { get; set; }
        public long ingredient { get; set; }
        public long amount { get; set; }
        public string unit { get; set; }
    }
}
