//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="name"></param>
        /// <param name="amount"></param>
        /// <param name="expirationDate"></param>
        /// <param name="deliveryDate"></param>
        /// <param name="supplier"></param>
        public Item(string name, long amount, DateTime? expirationDate, DateTime deliveryDate, string supplier) {
            Name = name;
            Amount = amount;
            ExpirationDate = expirationDate;
            DeliveryDate = deliveryDate;
            Supplier = supplier;
        }

        public Item() {
        }

        public long ID { get; set; }
        public string Name { get; set; }
        public long Amount { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Supplier { get; set; }
    }
}
