//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        public long uid { get; private set; }
        public string name { get; set; }
        public bool is_active { get; set; }
        public long minimum_amount { get; set; }
        public string unit { get; set; }
    }
}
