//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.IsDeleted = "False";
            this.WasteReports = new HashSet<WasteReport>();
        }
    
        public long UID { get; set; }
        public long Amount { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Supplier { get; set; }
        public long Reserved { get; set; }
        public string IsDeleted { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ItemType ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WasteReport> WasteReports { get; set; }
    }
}
