//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACLagerDatabase : DbContext
    {
        public ACLagerDatabase()
            : base("name=ACLagerDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Location> LocationSet { get; set; }
        public virtual DbSet<Ingredient> IngredientSet { get; set; }
        public virtual DbSet<Item> ItemSet { get; set; }
        public virtual DbSet<ItemType> ItemTypeSet { get; set; }
        public virtual DbSet<WorkOrder> WorkOrderSet { get; set; }
        public virtual DbSet<WorkOrderItem> WorkOrderItemSet { get; set; }
        public virtual DbSet<LogEntry> LogEntrySet { get; set; }
        public virtual DbSet<WasteReport> WasteReportSet { get; set; }
    }
}
