//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User() {
        }

        public long uid { get; private set; }
        [Required] public bool is_admin { get; set; }

        [Required(ErrorMessage = "Du skal indtaste et navn.")]
        public string name { get; set; }
        [Required] public bool is_active { get; set; }
    }
}
