//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.IsActive = true;
            this.WorkOrders = new HashSet<WorkOrder>();
            this.WasteReports = new HashSet<WasteReport>();
        }
    
        public long UID { get; set; }
        [Required]
        public bool IsActive { get; set; }
        [Required(ErrorMessage = "Du skal indtaste et navn.")]
        public string Name { get; set; }
        [Required]
        public bool IsAdmin { get; set; }
        [Required(ErrorMessage = "Du skal indtaste en kode.")]
        public short PIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WasteReport> WasteReports { get; set; }
    }
}
