//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteReport
    {
        public long UID { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public string ObjectData { get; set; }
    }
}
