//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteReport
    {
        public long UID { get; private set; }
        public System.DateTime Date { get; set; }
        public long Amount { get; set; }
        public Nullable<long> WorkOrderUID { get; set; }
        public long ItemUID { get; set; }
        public long UserUID { get; set; }
    
        public virtual WorkOrder WorkOrders { get; set; }
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
