//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrderItem()
        {
            this.Progress = 0;
        }
    
        public long UID { get; set; }
        public decimal Amount { get; set; }
        public long Progress { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Item Item { get; set; }
    }
}
