//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public long uid { get; set; }
        public System.DateTime due_date { get; set; }
        public bool is_complete { get; set; }
        public long completed_by { get; set; }
        public string type { get; set; }
        public long batch_number { get; set; }
    }
}
